---
# Install redis service

- name: Get Redis source code. >> http://download.redis.io/releases/redis-4.0.9.tar.gz
  get_url: url=http://download.redis.io/releases/redis-4.0.9.tar.gz dest=/opt/redis-4.0.9.tar.gz

- name: Extract archive
  unarchive:
        src: /opt/redis-4.0.9.tar.gz
        dest: /opt/

- name: Make install redis
  make: 
        chdir: /opt/redis-4.0.9
        target: install
  become: yes

- name: Add redis user
  user: name={{ redis_username }} shell=/sbin/nologin

- name: Create redis db directory
  file: path={{ redis_data_dir_path }} state=directory owner={{ redis_username }} group={{ redis_username }} mode=0755

- name: Create redis conf directory
  file: path=/etc/redis/ state=directory mode=0755

- name: Copy redis conf file to /etc/redis/6379.conf
  template:
        src: 6379.conf.j2
        dest: /etc/redis/{{ redis_bind_port }}.conf
        owner: root
        group: root
        mode: 0644

- name: Add redis control script 
  template:
        src: redis.service.j2
        dest: /usr/lib/systemd/system/redis.service
        owner: root
        group: root
        mode: 0644
  notify: 
        - daemon-reload
        - restart redis
        - enable redis
